using Ralven.Contracts;

namespace Ralven.Core.Catalog;

public sealed partial class ActionCatalog
{
    private static IReadOnlyList<OptimizationActionDefinition> CreateGamingAndPowerActions()
    {
        return
        [
            Define(
                OptimizationActionIds.EnableGameMode,
                "Ativar Modo de Jogo",
                "Ativa o recurso de jogos do Windows para priorização quando jogos estão em execução.",
                ActionCategory.WindowsGaming,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 5,
                expectedImpact: "Pode melhorar a consistência da sessão em sistemas compatíveis.",
                ActionOptionGate.EnableGameMode,
                detectionSummary: "Lê o valor AutoGameModeEnabled do registro do usuário atual.",
                confirmationSummary: "Confirma que o Modo de Jogo ficou habilitado após a gravação.",
                undoSummary: "Totalmente reversível: o valor anterior do registro é restaurado no rollback.",
                riskLimitations: "O ganho depende do hardware e da versão do Windows; pode não ter efeito perceptível."),
            Define(
                OptimizationActionIds.PreferHighPerformanceGpu,
                "Preferir GPU de alto desempenho",
                "Define a preferência gráfica do Windows para o launcher e os renderizadores detectados do FiveM Legacy.",
                ActionCategory.WindowsGaming,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 5,
                expectedImpact: "Evita o uso acidental da GPU econômica em computadores com múltiplas GPUs.",
                ActionOptionGate.PreferHighPerformanceGpu,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê a preferência gráfica registrada para o executável do FiveM.",
                confirmationSummary: "Confirma que a preferência de alto desempenho ficou registrada.",
                undoSummary: "Totalmente reversível: a preferência anterior é restaurada no rollback.",
                riskLimitations: "Só faz diferença em computadores com mais de uma GPU."),
            Define(
                OptimizationActionIds.DisableBackgroundCapture,
                "Desativar captura em segundo plano",
                "Desativa a gravação contínua em segundo plano do Windows sem remover o Game Bar.",
                ActionCategory.WindowsGaming,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                BalancedAndAggressive,
                requiresFiveMStopped: false,
                progressWeight: 4,
                expectedImpact: "Reduz atividade de captura quando ela estava habilitada.",
                ActionOptionGate.DisableBackgroundCapture,
                detectionSummary: "Lê o valor de gravação em segundo plano (Game DVR) do registro do usuário.",
                confirmationSummary: "Confirma que a captura em segundo plano ficou desabilitada.",
                undoSummary: "Totalmente reversível: o valor anterior é restaurado no rollback.",
                riskLimitations: "Não remove o Game Bar nem afeta gravações manuais que você iniciar."),
            Define(
                OptimizationActionIds.EnableSessionPerformancePowerPlan,
                "Ativar plano de energia de alto desempenho",
                "Ativa um plano de energia de desempenho na tomada e registra o estado anterior para rollback.",
                ActionCategory.Power,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.Administrator,
                BalancedAndAggressive,
                requiresFiveMStopped: false,
                progressWeight: 7,
                expectedImpact: "Reduz limitação de energia; aumenta consumo e temperatura até o rollback.",
                ActionOptionGate.UseSessionPerformancePowerPlan,
                requiresAcPower: true,
                detectionSummary: "Lê o plano de energia ativo e verifica se o computador está na tomada.",
                confirmationSummary: "Confirma que o plano de desempenho ficou ativo.",
                undoSummary: "Totalmente reversível: o plano anterior é restaurado no rollback.",
                riskLimitations: "Só é aplicado na tomada; aumenta consumo e temperatura enquanto ativo.",
                attemptWithoutElevationFirst: true),
            Define(
                OptimizationActionIds.AdjustPciExpressPowerManagement,
                "Ajustar PCI Express Link State Power Management",
                "Desativa a economia de energia dos links PCI Express (ASPM) no plano ativo. Isso evita transições de economia do link, mas o efeito perceptível depende do hardware e o consumo pode aumentar.",
                ActionCategory.Power,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                BalancedAndAggressive,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Evita transições de economia de energia dos links PCI Express; o ganho perceptível depende do hardware e o consumo pode aumentar.",
                ActionOptionGate.AdjustPciExpressPowerManagement,
                detectionSummary: "Lê os índices AC e DC da configuração ASPM do plano ativo pelas APIs nativas PowerReadACValueIndex e PowerReadDCValueIndex.",
                confirmationSummary: "Relê AC e DC e confirma Off (0) depois de reativar o plano.",
                undoSummary: "Totalmente reversível: restaura e confirma separadamente os valores AC e DC anteriores.",
                riskLimitations: "Nem todo hardware expõe essa configuração; nesse caso a ação é ignorada. Pode aumentar consumo e temperatura, e não há garantia de ganho perceptível em todo computador.",
                version: 2),
            Define(
                OptimizationActionIds.DisableMouseAcceleration,
                "Usar resposta consistente do ponteiro",
                "Desativa a aceleração do ponteiro do Windows sem alterar a velocidade escolhida pelo usuário.",
                ActionCategory.WindowsGaming,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AggressiveOnly,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Mantém a relação entre movimento físico e deslocamento do ponteiro em aplicativos que usam a configuração do Windows.",
                ActionOptionGate.UseConsistentPointerResponse,
                detectionSummary: "Lê os limiares e o nível de aceleração pela API SystemParametersInfo do Windows.",
                confirmationSummary: "Relê e confirma que os limiares e o nível de aceleração ficaram em zero.",
                undoSummary: "Totalmente reversível: restaura os três valores anteriores sem alterar a velocidade do ponteiro.",
                riskLimitations: "Muda a sensação do mouse no desktop; jogos com Raw Input podem ignorar esta configuração.")
        ];
    }

    private static IReadOnlyList<OptimizationActionDefinition> CreateAppearanceActions()
    {
        return
        [
            Define(
                OptimizationActionIds.ReduceMenuShowDelay,
                "Tornar menus do Windows mais responsivos",
                "Limita a 100 ms o atraso de abertura dos menus sem aumentar um valor menor já escolhido pelo usuário.",
                ActionCategory.Appearance,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                BalancedAndAggressive,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Torna a abertura de menus em cascata mais imediata.",
                ActionOptionGate.ReduceMenuShowDelay,
                detectionSummary: "Lê o atraso atual de abertura dos menus pela API oficial SystemParametersInfo do Windows.",
                confirmationSummary: "Relê e confirma que o atraso não ultrapassa 100 ms.",
                undoSummary: "Totalmente reversível: o atraso anterior é restaurado no rollback.",
                riskLimitations: "Muda somente a velocidade de abertura dos menus do Windows; o efeito percebido varia conforme o PC e o uso."),
            Define(
                OptimizationActionIds.ReduceWindowsVisualEffects,
                "Reduzir efeitos visuais do Windows",
                "Reduz animações e transparências preservando legibilidade e suavização de fontes.",
                ActionCategory.Appearance,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Aggressive],
                requiresFiveMStopped: false,
                progressWeight: 6,
                expectedImpact: "Reduz trabalho visual do desktop em computadores limitados.",
                ActionOptionGate.ReduceWindowsVisualEffects,
                detectionSummary: "Lê o estado atual de animações e transparências do Windows.",
                confirmationSummary: "Relê e confirma que os efeitos foram reduzidos preservando a suavização de fontes.",
                undoSummary: "Totalmente reversível: o estado anterior dos efeitos é restaurado no rollback.",
                riskLimitations: "Muda a aparência do desktop; preserva legibilidade e suavização de fontes.")
        ];
    }
}
